#!/usr/bin/env python3

import re
import csv
import operator
from collections import defaultdict

error_messages = defaultdict(int)
per_user = defaultdict(lambda: {'INFO': 0, 'ERROR': 0})

with open('syslog.log') as file:
    for line in file:
        if 'INFO' in line:
            username = re.search(r'\((.*)\)', line).group(1)
            per_user[username]['INFO'] += 1
        elif 'ERROR' in line:
            error = re.search(r'ERROR (.*) ', line).group(1)
            error_messages[error] += 1
            username = re.search(r'\((.*)\)', line).group(1)
            per_user[username]['ERROR'] += 1

sorted_errors = sorted(error_messages.items(), key=operator.itemgetter(1), reverse=True)

error_csv_rows = [('Error', 'Count')]
error_csv_rows.extend(sorted_errors)

with open('error_message.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(error_csv_rows)

sorted_users = sorted(per_user.items())

user_csv_rows = [('Username', 'INFO', 'ERROR')]
for username, counts in sorted_users:
    info_count = counts['INFO']
    error_count = counts['ERROR']
    user_csv_rows.append((username, info_count, error_count))

with open('user_statistics.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(user_csv_rows)
